### ISSUE TITLE
Any way to specify plugin install path?

### ISSUE THREAD

**Issue by zenopopovici** [pivvenit/acf-composer-bridge#4]
Seems not to take into account ```extra: { installer-paths: {..} } from package.json```

**Comment by schliflo** [comment]
As this project uses composer, the correct file to specify these settings is `composer.json` - `package.json` is for npm stuff 😉

**Comment by Qrious** [comment]
Hmm, i'll try to reproduce this. This might be due to the installer dependency we use.

**Comment by Qrious** [comment]
I've added new composer repository urls using the v3 prefix, as the fix is backwards incompatible (the installation directory changed by default). I've also updated the readme with the new URL's.

So in order to use the `extra: { installer-paths: {..} }` settings you have to use one of the following composer repository urls:
- https://pivvenit.github.io/acf-composer-bridge/composer/v3/wpackagist-plugin/
- https://pivvenit.github.io/acf-composer-bridge/composer/v3/wordpress-muplugin/
- https://pivvenit.github.io/acf-composer-bridge/composer/v3/wordpress-plugin/
- https://pivvenit.github.io/acf-composer-bridge/composer/v3/library/.

I'll close this issue, if you have any questions/issues, feel free to re-open or create a new issue.

**Comment by zenopopovici** [comment]
Wow... so fast! You're awesome @Qrious ! Thank you!
